//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainmeterStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Icons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RainmeterStudio.Resources.Icons", typeof(Icons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/page_white_star.png.
        /// </summary>
        internal static string DocumentCreateCommand {
            get {
                return ResourceManager.GetString("DocumentCreateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/32/text_generic.png.
        /// </summary>
        internal static string DocumentTemplate_Text {
            get {
                return ResourceManager.GetString("DocumentTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/project_star.png.
        /// </summary>
        internal static string ProjectCreateCommand {
            get {
                return ResourceManager.GetString("ProjectCreateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/project.png.
        /// </summary>
        internal static string ProjectItem_rsproj {
            get {
                return ResourceManager.GetString("ProjectItem_rsproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/text_generic.png.
        /// </summary>
        internal static string ProjectItem_txt {
            get {
                return ResourceManager.GetString("ProjectItem_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/folder.png.
        /// </summary>
        internal static string ProjectItemFolder {
            get {
                return ResourceManager.GetString("ProjectItemFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/page_white_delete.png.
        /// </summary>
        internal static string ProjectItemNone {
            get {
                return ResourceManager.GetString("ProjectItemNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/file_generic.png.
        /// </summary>
        internal static string ProjectItemUnknown {
            get {
                return ResourceManager.GetString("ProjectItemUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/minus.png.
        /// </summary>
        internal static string ProjectPanel_CollapseAllCommand {
            get {
                return ResourceManager.GetString("ProjectPanel_CollapseAllCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/plus.png.
        /// </summary>
        internal static string ProjectPanel_ExpandAllCommand {
            get {
                return ResourceManager.GetString("ProjectPanel_ExpandAllCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/view-refresh.png.
        /// </summary>
        internal static string ProjectPanel_RefreshCommand {
            get {
                return ResourceManager.GetString("ProjectPanel_RefreshCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/folder_explore.png.
        /// </summary>
        internal static string ProjectPanel_ShowAllFilesCommand {
            get {
                return ResourceManager.GetString("ProjectPanel_ShowAllFilesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/16/arrow_refresh_small.png.
        /// </summary>
        internal static string ProjectPanel_SyncWithActiveViewCommand {
            get {
                return ResourceManager.GetString("ProjectPanel_SyncWithActiveViewCommand", resourceCulture);
            }
        }
    }
}
