//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainmeterStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RainmeterStudio.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        public static string Category_Utility {
            get {
                return ResourceManager.GetString("Category_Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Dialog_Browse {
            get {
                return ResourceManager.GetString("Dialog_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Dialog_Create {
            get {
                return ResourceManager.GetString("Dialog_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string Dialog_FileType_AllFiles {
            get {
                return ResourceManager.GetString("Dialog_FileType_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RainmeterStudio project.
        /// </summary>
        public static string Dialog_FileType_Project {
            get {
                return ResourceManager.GetString("Dialog_FileType_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dialog_OK {
            get {
                return ResourceManager.GetString("Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project....
        /// </summary>
        public static string Dialog_OpenProject_Title {
            get {
                return ResourceManager.GetString("Dialog_OpenProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string DocumentCloseCommand_DisplayText {
            get {
                return ResourceManager.GetString("DocumentCloseCommand_DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close active document.
        /// </summary>
        public static string DocumentCloseCommand_ToolTip {
            get {
                return ResourceManager.GetString("DocumentCloseCommand_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File....
        /// </summary>
        public static string DocumentCreateCommand_DisplayText {
            get {
                return ResourceManager.GetString("DocumentCreateCommand_DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new file.
        /// </summary>
        public static string DocumentCreateCommand_ToolTip {
            get {
                return ResourceManager.GetString("DocumentCreateCommand_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor.
        /// </summary>
        public static string DocumentEditor_Text_Name {
            get {
                return ResourceManager.GetString("DocumentEditor_Text_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank text file.
        /// </summary>
        public static string DocumentFormat_TextFile_Description {
            get {
                return ResourceManager.GetString("DocumentFormat_TextFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file.
        /// </summary>
        public static string DocumentFormat_TextFile_Name {
            get {
                return ResourceManager.GetString("DocumentFormat_TextFile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainWindow_File {
            get {
                return ResourceManager.GetString("MainWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MainWindow_File_New {
            get {
                return ResourceManager.GetString("MainWindow_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MainWindow_File_Open {
            get {
                return ResourceManager.GetString("MainWindow_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Project....
        /// </summary>
        public static string ProjectCreateCommand_DisplayText {
            get {
                return ResourceManager.GetString("ProjectCreateCommand_DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new project.
        /// </summary>
        public static string ProjectCreateCommand_ToolTip {
            get {
                return ResourceManager.GetString("ProjectCreateCommand_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string ProjectCreateDialog_Location {
            get {
                return ResourceManager.GetString("ProjectCreateDialog_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set location as default.
        /// </summary>
        public static string ProjectCreateDialog_LocationDefault {
            get {
                return ResourceManager.GetString("ProjectCreateDialog_LocationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ProjectCreateDialog_Name {
            get {
                return ResourceManager.GetString("ProjectCreateDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string ProjectCreateDialog_Path {
            get {
                return ResourceManager.GetString("ProjectCreateDialog_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create directory for project.
        /// </summary>
        public static string ProjectCreateDialog_PathCreateFolder {
            get {
                return ResourceManager.GetString("ProjectCreateDialog_PathCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        public static string ProjectCreateDialog_Title {
            get {
                return ResourceManager.GetString("ProjectCreateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Project....
        /// </summary>
        public static string ProjectOpenCommand_DisplayText {
            get {
                return ResourceManager.GetString("ProjectOpenCommand_DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open existing project.
        /// </summary>
        public static string ProjectOpenCommand_ToolTip {
            get {
                return ResourceManager.GetString("ProjectOpenCommand_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string ProjectPanel_CollapseAllCommand_DisplayText {
            get {
                return ResourceManager.GetString("ProjectPanel_CollapseAllCommand_DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string ProjectPanel_CollapseAllCommand_ToolTip {
            get {
                return ResourceManager.GetString("ProjectPanel_CollapseAllCommand_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        public static string ProjectPanel_ExpandAllCommand_DisplayText {
            get {
                return ResourceManager.GetString("ProjectPanel_ExpandAllCommand_DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        public static string ProjectPanel_ExpandAllCommand_ToolTip {
            get {
                return ResourceManager.GetString("ProjectPanel_ExpandAllCommand_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ProjectPanel_RefreshCommand_DisplayText {
            get {
                return ResourceManager.GetString("ProjectPanel_RefreshCommand_DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ProjectPanel_RefreshCommand_ToolTip {
            get {
                return ResourceManager.GetString("ProjectPanel_RefreshCommand_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all files.
        /// </summary>
        public static string ProjectPanel_ShowAllFilesCommand_DisplayText {
            get {
                return ResourceManager.GetString("ProjectPanel_ShowAllFilesCommand_DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all files.
        /// </summary>
        public static string ProjectPanel_ShowAllFilesCommand_ToolTip {
            get {
                return ResourceManager.GetString("ProjectPanel_ShowAllFilesCommand_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with active view.
        /// </summary>
        public static string ProjectPanel_SyncWithActiveViewCommand_DisplayText {
            get {
                return ResourceManager.GetString("ProjectPanel_SyncWithActiveViewCommand_DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with active view.
        /// </summary>
        public static string ProjectPanel_SyncWithActiveViewCommand_ToolTip {
            get {
                return ResourceManager.GetString("ProjectPanel_SyncWithActiveViewCommand_ToolTip", resourceCulture);
            }
        }
    }
}
